name: Build official Chia Docker Image

on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'chia branch name to use'
        required: true
        default: 'main'
      image_tag:
        description: 'special tag for this image build'
        required: true
        default: 'latest'

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ADMIN_PAT }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Prune
        run: docker system prune --all

      - name: Build docker image
        run: docker build --no-cache --build-arg BRANCH=${{ github.event.inputs.upstream_branch }} -t ghcr.io/${{ github.actor }}/chia:${{ github.event.inputs.image_tag }} .

      - name: Push to github packages
        run: docker push ghcr.io/${{ github.actor }}/chia:${{ github.event.inputs.image_tag }}
